// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjmtqmwhkqrbscxsegjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbXRxbXdoa3FyYnNjeHNlZ2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjQ1MTQsImV4cCI6MjA1OTc0MDUxNH0.rF4GSIa5I8gVkI3geTtrMaf6KWCsZT2m5RE4Q9lAzn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);